{ pkgs, self, ... }:
let
  wallpaper = "${self}/assets/wallpaper.jpg";
in {
  home.packages = [ pkgs.hyprlock ];

  xdg.configFile."hypr/hyprlock.conf".text = ''
    # Source colors generated by wallust
    source = ~/.config/hypr/hyprlock-colors.conf

    general {
      hide_cursor = true
      grace = 0
      immediate_render = true
      ignore_empty_input = true
    }

    background {
      path = ${wallpaper}
      blur_passes = 2
      blur_size = 6
      brightness = 0.3
    }

    input-field {
      size = 300, 50
      outline_thickness = 2
      dots_size = 0.25
      dots_spacing = 0.3
      outer_color = $wallust_color8
      inner_color = $wallust_bg
      font_color = $wallust_fg
      check_color = $wallust_color4
      fail_color = $wallust_color1
      fail_text = <i>Wrong password</i>
      fail_timeout = 2000
      fail_transition = 300
      capslock_color = $wallust_color8
      numlock_color = $wallust_color8
      bothlock_color = $wallust_color8
      fade_on_empty = true
      placeholder_text = <i>Password...</i>
      hide_input = false
      rounding = 8
      position = 0, -50
      halign = center
      valign = center
    }

    label {
      text = $TIME
      color = $wallust_fg
      font_size = 72
      font_family = JetBrains Mono
      position = 0, 100
      halign = center
      valign = center
    }

    label {
      text = cmd[update:1000] date +"%A, %d de %B"
      color = $wallust_color8
      font_size = 16
      font_family = JetBrains Mono
      position = 0, 40
      halign = center
      valign = center
    }
  '';
}
