{ config, pkgs, ... }: {
  programs.rofi = {
    enable = true;
    package = pkgs.rofi;

    terminal = "${pkgs.kitty}/bin/kitty";

    extraConfig = {
      modi = "drun,run";
      show-icons = true;
      icon-theme = "Adwaita";
      drun-display-format = "{name}";
      disable-history = false;
      display-drun = "";
      matching = "fuzzy";
      sort = true;
      sorting-method = "fzf";
    };

    theme = let
      inherit (config.lib.formats.rasi) mkLiteral;
    in {
      # Import colors generated by wallust
      "@import" = "colors.rasi";

      "*" = {
        font = "JetBrains Mono 13";
        # Colors are imported from colors.rasi (generated by wallust)
        # Use wallust-* variables defined there
        background = mkLiteral "@wallust-bg";
        background-alt = mkLiteral "@wallust-bg-alt";
        foreground = mkLiteral "@wallust-fg";
        selected = mkLiteral "@wallust-selected";
        active = mkLiteral "@wallust-active";
        urgent = mkLiteral "@wallust-urgent";
      };

      "window" = {
        width = mkLiteral "600px";
        padding = mkLiteral "0px";
        border = mkLiteral "1px solid";
        border-color = mkLiteral "@wallust-bg-alt";
        border-radius = mkLiteral "12px";
        background-color = mkLiteral "@background";
        location = mkLiteral "center";
        anchor = mkLiteral "center";
      };

      "mainbox" = {
        background-color = mkLiteral "transparent";
        children = map mkLiteral [ "inputbar" "listview" ];
      };

      "inputbar" = {
        background-color = mkLiteral "transparent";
        text-color = mkLiteral "@foreground";
        padding = mkLiteral "16px 20px";
        children = map mkLiteral [ "prompt" "entry" ];
      };

      "prompt" = {
        background-color = mkLiteral "transparent";
        text-color = mkLiteral "@foreground";
        padding = mkLiteral "0px 12px 0px 0px";
      };

      "entry" = {
        background-color = mkLiteral "transparent";
        text-color = mkLiteral "@foreground";
        placeholder = "Search...";
        placeholder-color = mkLiteral "@wallust-bg-alt";
      };

      "listview" = {
        background-color = mkLiteral "transparent";
        columns = 1;
        lines = 8;
        cycle = false;
        dynamic = true;
        scrollbar = false;
        layout = mkLiteral "vertical";
        padding = mkLiteral "0px 8px 8px 8px";
      };

      "element" = {
        background-color = mkLiteral "transparent";
        text-color = mkLiteral "@foreground";
        padding = mkLiteral "10px 16px";
        border-radius = mkLiteral "8px";
        spacing = mkLiteral "12px";
      };

      "element selected" = {
        background-color = mkLiteral "@selected";
        text-color = mkLiteral "@foreground";
      };

      "element-icon" = {
        size = mkLiteral "24px";
        background-color = mkLiteral "transparent";
      };

      "element-text" = {
        background-color = mkLiteral "transparent";
        text-color = mkLiteral "inherit";
        vertical-align = mkLiteral "0.5";
      };
    };
  };
}
