{ pkgs, ... }: {
  home.packages = [ pkgs.swaynotificationcenter ];

  xdg.configFile."swaync/config.json".text = builtins.toJSON {
    positionX = "right";
    positionY = "top";
    control-center-width = 400;
    control-center-height = 600;
    fit-to-screen = false;
    layer = "overlay";
    cssPriority = "user";
    notification-icon-size = 48;
    notification-body-image-height = 100;
    notification-body-image-width = 200;
    timeout = 10;
    timeout-low = 5;
    timeout-critical = 0;
    notification-window-width = 350;
    keyboard-shortcuts = true;
    image-visibility = "when-available";
    transition-time = 200;
    hide-on-clear = true;
    hide-on-action = true;
    widgets = [
      "title"
      "dnd"
      "notifications"
    ];
    widget-config = {
      title = {
        text = "Notifications";
        clear-all-button = true;
      };
      dnd = {
        text = "Do Not Disturb";
      };
    };
  };

  xdg.configFile."swaync/style.css".text = ''
    /* Import colors generated by wallust */
    @import url("colors.css");

    * {
      font-family: "JetBrains Mono";
      font-size: 13px;
    }

    .control-center {
      background: alpha(@background, 0.95);
      border: 1px solid @color8;
      border-radius: 12px;
      padding: 12px;
    }

    .notification {
      background: @color0;
      border: 1px solid @color8;
      border-radius: 8px;
      margin: 6px;
      padding: 12px;
    }

    .notification-content {
      color: @foreground;
    }

    .notification .summary {
      color: @foreground;
      font-weight: bold;
    }

    .notification .body {
      color: alpha(@foreground, 0.7);
    }

    .notification.critical {
      border-color: @color1;
    }

    .widget-title {
      color: @foreground;
      font-weight: bold;
      padding: 8px;
    }

    .widget-title > button {
      background: @color0;
      color: @foreground;
      border: none;
      border-radius: 6px;
      padding: 4px 12px;
    }

    .widget-title > button:hover {
      background: @color8;
    }

    .widget-dnd {
      color: @foreground;
      padding: 8px;
    }

    .widget-dnd > switch {
      background: @color0;
      border-radius: 12px;
    }

    .widget-dnd > switch:checked {
      background: @color4;
    }

    .widget-dnd > switch slider {
      background: @foreground;
      border-radius: 50%;
    }
  '';
}
