{ pkgs, ... }:
let
  # Hyprland colors template
  hyprlandTemplate = ''
    # Auto-generated by wallust - do not edit manually
    $wallust_bg = rgb({{background | strip}})
    $wallust_fg = rgb({{foreground | strip}})
    $wallust_cursor = rgb({{cursor | strip}})
    $wallust_color0 = rgb({{color0 | strip}})
    $wallust_color1 = rgb({{color1 | strip}})
    $wallust_color2 = rgb({{color2 | strip}})
    $wallust_color3 = rgb({{color3 | strip}})
    $wallust_color4 = rgb({{color4 | strip}})
    $wallust_color5 = rgb({{color5 | strip}})
    $wallust_color6 = rgb({{color6 | strip}})
    $wallust_color7 = rgb({{color7 | strip}})
    $wallust_color8 = rgb({{color8 | strip}})
    $wallust_color9 = rgb({{color9 | strip}})
    $wallust_color10 = rgb({{color10 | strip}})
    $wallust_color11 = rgb({{color11 | strip}})
    $wallust_color12 = rgb({{color12 | strip}})
    $wallust_color13 = rgb({{color13 | strip}})
    $wallust_color14 = rgb({{color14 | strip}})
    $wallust_color15 = rgb({{color15 | strip}})

    general {
      col.active_border = rgb({{color4 | saturate(0.5) | strip}}) rgb({{color5 | saturate(0.5) | strip}}) 45deg
      col.inactive_border = rgba({{color0 | strip}}aa)
    }
  '';

  # Waybar CSS variables template
  waybarTemplate = ''
    /* Auto-generated by wallust - do not edit manually */
    @define-color background {{background}};
    @define-color foreground {{foreground}};
    @define-color cursor {{cursor}};
    @define-color color0 {{color0}};
    @define-color color1 {{color1}};
    @define-color color2 {{color2}};
    @define-color color3 {{color3}};
    @define-color color4 {{color4}};
    @define-color color5 {{color5}};
    @define-color color6 {{color6}};
    @define-color color7 {{color7}};
    @define-color color8 {{color8}};
    @define-color color9 {{color9}};
    @define-color color10 {{color10}};
    @define-color color11 {{color11}};
    @define-color color12 {{color12}};
    @define-color color13 {{color13}};
    @define-color color14 {{color14}};
    @define-color color15 {{color15}};
  '';

  # Kitty colors template
  kittyTemplate = ''
    # Auto-generated by wallust - do not edit manually
    cursor {{cursor}}
    background {{background}}
    foreground {{foreground}}

    color0 {{color0}}
    color1 {{color1}}
    color2 {{color2}}
    color3 {{color3}}
    color4 {{color4}}
    color5 {{color5}}
    color6 {{color6}}
    color7 {{color7}}
    color8 {{color8}}
    color9 {{color9}}
    color10 {{color10}}
    color11 {{color11}}
    color12 {{color12}}
    color13 {{color13}}
    color14 {{color14}}
    color15 {{color15}}
  '';

  # Rofi colors template (rasi format)
  rofiTemplate = ''
    /* Auto-generated by wallust - do not edit manually */
    * {
      wallust-bg: {{background}};
      wallust-bg-alt: {{color0}};
      wallust-fg: {{foreground}};
      wallust-selected: {{color4}}26;
      wallust-active: {{foreground}};
      wallust-urgent: {{color1}};
    }
  '';

  # SwayNC CSS variables template
  swayncTemplate = ''
    /* Auto-generated by wallust - do not edit manually */
    @define-color background {{background}};
    @define-color foreground {{foreground}};
    @define-color color0 {{color0}};
    @define-color color1 {{color1}};
    @define-color color2 {{color2}};
    @define-color color3 {{color3}};
    @define-color color4 {{color4}};
    @define-color color5 {{color5}};
    @define-color color6 {{color6}};
    @define-color color7 {{color7}};
    @define-color color8 {{color8}};
  '';

  # Hyprlock colors template
  hyprlockTemplate = ''
    # Auto-generated by wallust - do not edit manually
    $wallust_bg = rgb({{background | strip}})
    $wallust_fg = rgb({{foreground | strip}})
    $wallust_color0 = rgb({{color0 | strip}})
    $wallust_color1 = rgb({{color1 | strip}})
    $wallust_color4 = rgb({{color4 | strip}})
    $wallust_color8 = rgb({{color8 | strip}})
  '';

  # GTK4 CSS variables template (libadwaita)
  gtk4Template = ''
    /* Auto-generated by wallust - do not edit manually */
    @define-color accent_bg_color {{color4}};
    @define-color accent_fg_color {{foreground}};
    @define-color accent_color {{color4}};
    @define-color destructive_bg_color {{color1}};
    @define-color destructive_fg_color {{foreground}};
    @define-color destructive_color {{color1}};
    @define-color success_bg_color {{color2}};
    @define-color success_fg_color {{foreground}};
    @define-color success_color {{color2}};
    @define-color warning_bg_color {{color3}};
    @define-color warning_fg_color {{background}};
    @define-color warning_color {{color3}};
    @define-color error_bg_color {{color1}};
    @define-color error_fg_color {{foreground}};
    @define-color error_color {{color1}};
    @define-color window_bg_color {{background}};
    @define-color window_fg_color {{foreground}};
    @define-color view_bg_color {{background | lighten(0.02)}};
    @define-color view_fg_color {{foreground}};
    @define-color headerbar_bg_color {{background | lighten(0.05)}};
    @define-color headerbar_fg_color {{foreground}};
    @define-color headerbar_backdrop_color {{background}};
    @define-color headerbar_border_color {{foreground}};
    @define-color card_bg_color {{background | lighten(0.08)}};
    @define-color card_fg_color {{foreground}};
    @define-color popover_bg_color {{background | lighten(0.1)}};
    @define-color popover_fg_color {{foreground}};
    @define-color dialog_bg_color {{background | lighten(0.1)}};
    @define-color dialog_fg_color {{foreground}};
    @define-color sidebar_bg_color {{background | lighten(0.03)}};
    @define-color sidebar_fg_color {{foreground}};
  '';

  # GTK3 uses same format as GTK4
  gtk3Template = gtk4Template;

  # Shell colors template (LS_COLORS and EZA_COLORS)
  # Uses true color (38;2;R;G;B format) for LS_COLORS
  shellColorsTemplate = ''
    # Auto-generated by wallust - do not edit manually
    # LS_COLORS with true color support
    export LS_COLORS="di=38;2;{{color4 | red}};{{color4 | green}};{{color4 | blue}}:ln=38;2;{{color6 | red}};{{color6 | green}};{{color6 | blue}}:so=38;2;{{color5 | red}};{{color5 | green}};{{color5 | blue}}:pi=38;2;{{color3 | red}};{{color3 | green}};{{color3 | blue}}:ex=38;2;{{color2 | red}};{{color2 | green}};{{color2 | blue}}:bd=38;2;{{color3 | red}};{{color3 | green}};{{color3 | blue}}:cd=38;2;{{color3 | red}};{{color3 | green}};{{color3 | blue}}:su=38;2;{{color1 | red}};{{color1 | green}};{{color1 | blue}}:sg=38;2;{{color1 | red}};{{color1 | green}};{{color1 | blue}}:tw=38;2;{{color4 | red}};{{color4 | green}};{{color4 | blue}}:ow=38;2;{{color4 | red}};{{color4 | green}};{{color4 | blue}}:*.tar=38;2;{{color1 | red}};{{color1 | green}};{{color1 | blue}}:*.zip=38;2;{{color1 | red}};{{color1 | green}};{{color1 | blue}}:*.gz=38;2;{{color1 | red}};{{color1 | green}};{{color1 | blue}}:*.bz2=38;2;{{color1 | red}};{{color1 | green}};{{color1 | blue}}:*.xz=38;2;{{color1 | red}};{{color1 | green}};{{color1 | blue}}:*.jpg=38;2;{{color5 | red}};{{color5 | green}};{{color5 | blue}}:*.jpeg=38;2;{{color5 | red}};{{color5 | green}};{{color5 | blue}}:*.png=38;2;{{color5 | red}};{{color5 | green}};{{color5 | blue}}:*.gif=38;2;{{color5 | red}};{{color5 | green}};{{color5 | blue}}:*.webp=38;2;{{color5 | red}};{{color5 | green}};{{color5 | blue}}:*.svg=38;2;{{color5 | red}};{{color5 | green}};{{color5 | blue}}:*.mp3=38;2;{{color6 | red}};{{color6 | green}};{{color6 | blue}}:*.flac=38;2;{{color6 | red}};{{color6 | green}};{{color6 | blue}}:*.wav=38;2;{{color6 | red}};{{color6 | green}};{{color6 | blue}}:*.mp4=38;2;{{color5 | red}};{{color5 | green}};{{color5 | blue}}:*.mkv=38;2;{{color5 | red}};{{color5 | green}};{{color5 | blue}}:*.avi=38;2;{{color5 | red}};{{color5 | green}};{{color5 | blue}}"

    # EZA_COLORS uses hex format
    export EZA_COLORS="di={{color4 | strip}}:ln={{color6 | strip}}:so={{color5 | strip}}:pi={{color3 | strip}}:ex={{color2 | strip}}:bd={{color3 | strip}}:cd={{color3 | strip}}:su={{color1 | strip}}:sg={{color1 | strip}}:tw={{color4 | strip}}:ow={{color4 | strip}}:ur={{foreground | strip}}:uw={{foreground | strip}}:ux={{foreground | strip}}:ue={{foreground | strip}}:gr={{foreground | strip}}:gw={{foreground | strip}}:gx={{foreground | strip}}:tr={{foreground | strip}}:tw={{foreground | strip}}:tx={{foreground | strip}}:da={{color8 | strip}}:sn={{color2 | strip}}:sb={{color2 | strip}}:uu={{color3 | strip}}:un={{color1 | strip}}:gu={{color3 | strip}}:gn={{color1 | strip}}"
  '';

in {
  home.packages = [ pkgs.wallust ];

  # Wallust configuration and templates
  xdg.configFile = {
    "wallust/wallust.toml".text = ''
      [wallust]
      backend = "resized"
      color_space = "labmixed"
      palette = "dark16"
      check_contrast = true

      [templates]
      hyprland = { template = "hyprland.conf", target = "~/.config/hypr/colors.conf" }
      waybar = { template = "waybar.css", target = "~/.config/waybar/colors.css" }
      kitty = { template = "kitty.conf", target = "~/.config/kitty/colors.conf" }
      rofi = { template = "rofi.rasi", target = "~/.config/rofi/colors.rasi" }
      swaync = { template = "swaync.css", target = "~/.config/swaync/colors.css" }
      hyprlock = { template = "hyprlock.conf", target = "~/.config/hypr/hyprlock-colors.conf" }
      gtk4 = { template = "gtk4.css", target = "~/.config/gtk-4.0/gtk.css" }
      gtk3 = { template = "gtk3.css", target = "~/.config/gtk-3.0/gtk.css" }
      shell = { template = "shell.sh", target = "~/.config/shell/colors.sh" }
    '';
    # Templates
    "wallust/templates/hyprland.conf".text = hyprlandTemplate;
    "wallust/templates/waybar.css".text = waybarTemplate;
    "wallust/templates/kitty.conf".text = kittyTemplate;
    "wallust/templates/rofi.rasi".text = rofiTemplate;
    "wallust/templates/swaync.css".text = swayncTemplate;
    "wallust/templates/hyprlock.conf".text = hyprlockTemplate;
    "wallust/templates/gtk4.css".text = gtk4Template;
    "wallust/templates/gtk3.css".text = gtk3Template;
    "wallust/templates/shell.sh".text = shellColorsTemplate;
  };

  # Fallback color files created via activation script
  # These are created only if they don't exist, allowing wallust to overwrite them
  home.activation.wallustFallbackColors = ''
    # Create directories
    mkdir -p "$HOME/.config/hypr"
    mkdir -p "$HOME/.config/waybar"
    mkdir -p "$HOME/.config/rofi"
    mkdir -p "$HOME/.config/swaync"
    mkdir -p "$HOME/.config/kitty"
    mkdir -p "$HOME/.config/shell"

    # Hyprland colors
    [ ! -f "$HOME/.config/hypr/colors.conf" ] && cat > "$HOME/.config/hypr/colors.conf" << 'FALLBACK'
# Fallback colors - will be overwritten by wallust
$wallust_bg = rgb(1a1a1a)
$wallust_fg = rgb(e0e0e0)
$wallust_cursor = rgb(e0e0e0)
$wallust_color0 = rgb(1a1a1a)
$wallust_color1 = rgb(f38ba8)
$wallust_color2 = rgb(a6e3a1)
$wallust_color3 = rgb(f9e2af)
$wallust_color4 = rgb(89b4fa)
$wallust_color5 = rgb(cba6f7)
$wallust_color6 = rgb(94e2d5)
$wallust_color7 = rgb(e0e0e0)
$wallust_color8 = rgb(595959)
$wallust_color9 = rgb(f38ba8)
$wallust_color10 = rgb(a6e3a1)
$wallust_color11 = rgb(f9e2af)
$wallust_color12 = rgb(89b4fa)
$wallust_color13 = rgb(cba6f7)
$wallust_color14 = rgb(94e2d5)
$wallust_color15 = rgb(e0e0e0)

general {
  col.active_border = rgb(89b4fa) rgb(cba6f7) 45deg
  col.inactive_border = rgba(1a1a1aaa)
}
FALLBACK

    # Hyprlock colors
    [ ! -f "$HOME/.config/hypr/hyprlock-colors.conf" ] && cat > "$HOME/.config/hypr/hyprlock-colors.conf" << 'FALLBACK'
# Fallback colors - will be overwritten by wallust
$wallust_bg = rgb(1a1a1a)
$wallust_fg = rgb(e0e0e0)
$wallust_color0 = rgb(1a1a1a)
$wallust_color1 = rgb(f38ba8)
$wallust_color4 = rgb(89b4fa)
$wallust_color8 = rgb(595959)
FALLBACK

    # Waybar colors
    [ ! -f "$HOME/.config/waybar/colors.css" ] && cat > "$HOME/.config/waybar/colors.css" << 'FALLBACK'
/* Fallback colors - will be overwritten by wallust */
@define-color background #1a1a1a;
@define-color foreground #e0e0e0;
@define-color cursor #e0e0e0;
@define-color color0 #1a1a1a;
@define-color color1 #f38ba8;
@define-color color2 #a6e3a1;
@define-color color3 #f9e2af;
@define-color color4 #89b4fa;
@define-color color5 #cba6f7;
@define-color color6 #94e2d5;
@define-color color7 #e0e0e0;
@define-color color8 #595959;
@define-color color9 #f38ba8;
@define-color color10 #a6e3a1;
@define-color color11 #f9e2af;
@define-color color12 #89b4fa;
@define-color color13 #cba6f7;
@define-color color14 #94e2d5;
@define-color color15 #e0e0e0;
FALLBACK

    # Rofi colors
    [ ! -f "$HOME/.config/rofi/colors.rasi" ] && cat > "$HOME/.config/rofi/colors.rasi" << 'FALLBACK'
/* Fallback colors - will be overwritten by wallust */
* {
  wallust-bg: #1a1a1a;
  wallust-bg-alt: #1a1a1a;
  wallust-fg: #e0e0e0;
  wallust-selected: #89b4fa26;
  wallust-active: #e0e0e0;
  wallust-urgent: #f38ba8;
}
FALLBACK

    # SwayNC colors
    [ ! -f "$HOME/.config/swaync/colors.css" ] && cat > "$HOME/.config/swaync/colors.css" << 'FALLBACK'
/* Fallback colors - will be overwritten by wallust */
@define-color background #1a1a1a;
@define-color foreground #e0e0e0;
@define-color color0 #1a1a1a;
@define-color color1 #f38ba8;
@define-color color2 #a6e3a1;
@define-color color3 #f9e2af;
@define-color color4 #89b4fa;
@define-color color5 #cba6f7;
@define-color color6 #94e2d5;
@define-color color7 #e0e0e0;
@define-color color8 #595959;
FALLBACK

    # Kitty colors
    [ ! -f "$HOME/.config/kitty/colors.conf" ] && cat > "$HOME/.config/kitty/colors.conf" << 'FALLBACK'
# Fallback colors - will be overwritten by wallust
cursor #e0e0e0
background #1a1a1a
foreground #e0e0e0
color0 #1a1a1a
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #cba6f7
color6 #94e2d5
color7 #e0e0e0
color8 #595959
color9 #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #cba6f7
color14 #94e2d5
color15 #e0e0e0
FALLBACK

    # Shell colors
    [ ! -f "$HOME/.config/shell/colors.sh" ] && cat > "$HOME/.config/shell/colors.sh" << 'FALLBACK'
# Fallback colors - will be overwritten by wallust
export LS_COLORS="di=38;2;137;180;250:ln=38;2;148;226;213:so=38;2;203;166;247:pi=38;2;249;226;175:ex=38;2;166;227;161:bd=38;2;249;226;175:cd=38;2;249;226;175:su=38;2;243;139;168:sg=38;2;243;139;168:tw=38;2;137;180;250:ow=38;2;137;180;250"
export EZA_COLORS="di=89b4fa:ln=94e2d5:so=cba6f7:pi=f9e2af:ex=a6e3a1:bd=f9e2af:cd=f9e2af:su=f38ba8:sg=f38ba8:tw=89b4fa:ow=89b4fa:da=595959:sn=a6e3a1:sb=a6e3a1:uu=f9e2af:un=f38ba8:gu=f9e2af:gn=f38ba8"
FALLBACK

  '';
}
